data_dir_on_host: "../../data/"
data_dir: "/data"

logging_output_directory_on_host: "/tmp/multi_person"
logging_path: "/tmp/log.html"

demo:
  # image_path: "/data/test_images_modified/100809462_target.jpg"
  image_path: "/data/test_images/106050921_original.jpg"
  # image_path: "./demo_image/demo3.jpg"

  images_directory: "/data/body_retouched_by_vb_editor/"
